apiVersion: v1
kind: Pod
spec:
  containers:
    - name: azure-pyspark
      securityContext:
        privileged: true
      resources:
        limits:
          cpu: "2"
        requests:
          cpu: "1"
